name: project_mad
description: A simple Flutter app demonstrating Dart and Flutter basics.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  geolocator: ^13.0.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  firebase_core: ^4.8.0
  firebase_auth: ^6.5.0
  cloud_firestore: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
