// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV-tPtMo7rcOmXMviFRk2ECpryjdyYK_I',
    appId: '1:971951750524:web:9231a94e06edd3bff538f9',
    messagingSenderId: '971951750524',
    projectId: 'coastguardapp',
    authDomain: 'coastguardapp.firebaseapp.com',
    databaseURL: 'https://coastguardapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coastguardapp.firebasestorage.app',
    measurementId: 'G-ETTRVNSV66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKV4D3ETrdzNZ_kqI1MAtTXgvwCligj5E',
    appId: '1:971951750524:android:7df219d5d41ebe36f538f9',
    messagingSenderId: '971951750524',
    projectId: 'coastguardapp',
    databaseURL: 'https://coastguardapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coastguardapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpLosE1CAwA2ql6tRaw6p1PViKvHLOepo',
    appId: '1:971951750524:ios:08ce41e7a5102d49f538f9',
    messagingSenderId: '971951750524',
    projectId: 'coastguardapp',
    databaseURL: 'https://coastguardapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coastguardapp.firebasestorage.app',
    iosClientId: '971951750524-6s5jopeurnc31s65dq11fvvgbudrigou.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpLosE1CAwA2ql6tRaw6p1PViKvHLOepo',
    appId: '1:971951750524:ios:08ce41e7a5102d49f538f9',
    messagingSenderId: '971951750524',
    projectId: 'coastguardapp',
    databaseURL: 'https://coastguardapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coastguardapp.firebasestorage.app',
    iosClientId: '971951750524-6s5jopeurnc31s65dq11fvvgbudrigou.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzlNa8IQ3CHBYlloX_hQ_A9i_07BSw1qk',
    appId: '1:971951750524:web:9231a94e06edd3bff538f9',
    messagingSenderId: '28020225963',
    projectId: 'coastguardapp',
    authDomain: 'coastguardapp.firebaseapp.com',
    storageBucket: 'coastguardapp.firebasestorage.app',
    measurementId: 'G-8YPSR87CJ3',
  );

}