// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzlNa8IQ3CHBYlloX_hQ_A9i_07BSw1qk',
    appId: '1:28020225963:web:a42cb124b82e25429144ee',
    messagingSenderId: '28020225963',
    projectId: 'coastalapp-6c8f6',
    authDomain: 'coastalapp-6c8f6.firebaseapp.com',
    storageBucket: 'coastalapp-6c8f6.firebasestorage.app',
    measurementId: 'G-7N5BJ97PCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgOqcfPAe1MHMh6CRTfdtUx-zrWLXAKuE',
    appId: '1:28020225963:android:fcb3fe1f725d37b89144ee',
    messagingSenderId: '28020225963',
    projectId: 'coastalapp-6c8f6',
    storageBucket: 'coastalapp-6c8f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqBqaaSCSiOlHeT6F4zL2dYpelAGVyQwk',
    appId: '1:28020225963:ios:999f9d9fee6625b49144ee',
    messagingSenderId: '28020225963',
    projectId: 'coastalapp-6c8f6',
    storageBucket: 'coastalapp-6c8f6.firebasestorage.app',
    iosBundleId: 'com.example.projectMad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqBqaaSCSiOlHeT6F4zL2dYpelAGVyQwk',
    appId: '1:28020225963:ios:999f9d9fee6625b49144ee',
    messagingSenderId: '28020225963',
    projectId: 'coastalapp-6c8f6',
    storageBucket: 'coastalapp-6c8f6.firebasestorage.app',
    iosBundleId: 'com.example.projectMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzlNa8IQ3CHBYlloX_hQ_A9i_07BSw1qk',
    appId: '1:28020225963:web:ef1d12887b4f02a19144ee',
    messagingSenderId: '28020225963',
    projectId: 'coastalapp-6c8f6',
    authDomain: 'coastalapp-6c8f6.firebaseapp.com',
    storageBucket: 'coastalapp-6c8f6.firebasestorage.app',
    measurementId: 'G-8YPSR87CJ3',
  );

}